server:
  port: 8001
spring:
  application:
    name: apirouteservice
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka/

zuul:
  routes:
    userservice:
      path: /user/**
      serviceId: userservice


#zuul.routes.userservice.stripPrefix=true
#zuul.routes.userservice.url=http://localhost:9001/user
#zuul.routes.orgservice.path=/org/**
#zuul.routes.orgservice.stripPrefix=true
#zuul.routes.orgservice.url=http://localhost:9002/org